import os
import sys
import platform

OS_NAME = platform.system();
LIB_DIR=os.environ['LIB_DIR'];
BIN_DIR=os.environ['BIN_DIR'];

env=DefaultEnvironment().Clone()
SOURCES=Glob('litehtml/src/*.cpp') + Glob('litehtml/src/gumbo/*.c')

env.Library(os.path.join(LIB_DIR, 'litehtml'), SOURCES);

